export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
// export * from "@/pages/dashboard/notification";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/batuan";
export * from "@/pages/dashboard/sumberdayageologi";
export * from "@/pages/dashboard/fosil";
export * from "@/pages/dashboard/FosilTabel";
export * from "@/pages/dashboard/SdgTabel";
export * from "@/pages/dashboard/batuan_edit";
export * from "@/pages/dashboard/fosiledit";
export * from "@/pages/dashboard/sdgedit";
export * from "@/pages/dashboard/NotFound";
